import gender from '../enum/gender.enum';

export default class UserData {
  readonly id: string[] = [
    'WMLdDSts',
    'BtcSLU4W',
    'EF5M2jr9',
    'rDGqrkWH',
    'x5CjScLd',
    '0ap-rtRM',
    'eWjzpF6D',
    'RuTxgtYG',
    'jeE8Zr5p',
    'JDKlB9A4',
    'lzrnWKTr',
    'ESJJKyWI',
    'MflSf3GW',
    'hAP7qZbS',
    'F8_UB0bj',
    '4XeeK5hO',
    'tibeb3Jg',
    '1s2MiMjw',
    'gBQXv-8v',
    'xPdLJncz',
  ];

  readonly firstName: string[] = [
    'Jam',
    'Sanford',
    'Enrique',
    'Leopoldo',
    'Jason',
    'Dudley',
    'Stefan',
    'Dannie',
    'Hershel',
    'Bruno',
    'Carol',
    'Royal',
    'Hamza',
    'Rodney',
    'Brooks',
    'Philip',
    'Ian',
    'Zachary',
    'Cason',
    'Jacob',
    'Frederick',
    'Shamar',
  ];

  readonly LastName: string[] = [
    'Bonifacio',
    'Barrett',
    'Bradshaw',
    'Chavez',
    'Aguilar',
    'Pollard',
    'Reed',
    'Juarez',
    'Mclean',
    'Huffman',
    'Peters',
    'Boyd',
    'Chase',
    'Foley',
    'Weaver',
    'Hebert',
    'Cantu',
    'Obrien',
    'Schmidt',
    'Greer',
  ];

  readonly course: string[] = [
    'BSSE',
    'BSME',
    'BSCE',
    'BSEE',
    'BSPKGE',
    'BSECE',
  ];

  readonly phoneNumber: string[] = [
    '(810) 695-3919',
    '(957) 845-6373',
    '(205) 842-5092',
    '(930) 315-2334',
    '(351) 346-7935',
    '(529) 561-9052',
    '(408) 894-1023',
    '(314) 322-3337',
    '(557) 310-3672',
    '(821) 448-2911',
    '(204) 597-1883',
    '(903) 602-0620',
    '(581) 566-8956',
    '(257) 726-0580',
    '(392) 362-7996',
    '(608) 998-1125',
    '(825) 760-8743',
    '(418) 811-8895',
    '(381) 684-3242',
    '(434) 320-2806',
  ];

  readonly email: string[] = [
    'nweaver@me.com',
    'yfreund@att.net',
    'satishr@hotmail.com',
    'dkasak@sbcglobal.net',
    'fwitness@sbcglobal.net',
    'staikos@msn.com',
    'wsnyder@outlook.com',
    'webteam@verizon.net',
    'breegster@optonline.net',
    'rwelty@aol.com',
    'timtroyr@hotmail.com',
    'tmaek@comcast.net',
    'haddawy@msn.com',
    'andrei@comcast.net',
    'smpeters@yahoo.ca',
    'tarreau@optonline.net',
    'uncle@hotmail.com',
    'draper@verizon.net',
    'cantu@live.com',
    'parasite@att.net',
  ];

  readonly gender: gender[] = [gender.M, gender.F];
}
